Caller:
    type: entity
    table: caller
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        adress:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        phone:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: ''
        mail:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
