Language:
    type: entity
    table: language
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        isoCode:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: iso_code
    lifecycleCallbacks: {  }
